/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchHistoryRouteImport } from './routes/search-history'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ReviewHistoryRouteImport } from './routes/review-history'
import { Route as ReviewGenerateRouteImport } from './routes/review-generate'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as AdvancedSearchRouteImport } from './routes/advanced-search'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as LiteratureIdRouteImport } from './routes/literature.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminStatisticsRouteImport } from './routes/admin.statistics'
import { Route as AdminLlmConfigsRouteImport } from './routes/admin.llm-configs'
import { Route as AdminLiteraturesRouteImport } from './routes/admin.literatures'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'

const SearchHistoryRoute = SearchHistoryRouteImport.update({
  id: '/search-history',
  path: '/search-history',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewHistoryRoute = ReviewHistoryRouteImport.update({
  id: '/review-history',
  path: '/review-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewGenerateRoute = ReviewGenerateRouteImport.update({
  id: '/review-generate',
  path: '/review-generate',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvancedSearchRoute = AdvancedSearchRouteImport.update({
  id: '/advanced-search',
  path: '/advanced-search',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiteratureIdRoute = LiteratureIdRouteImport.update({
  id: '/literature/$id',
  path: '/literature/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStatisticsRoute = AdminStatisticsRouteImport.update({
  id: '/admin/statistics',
  path: '/admin/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLlmConfigsRoute = AdminLlmConfigsRouteImport.update({
  id: '/admin/llm-configs',
  path: '/admin/llm-configs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLiteraturesRoute = AdminLiteraturesRouteImport.update({
  id: '/admin/literatures',
  path: '/admin/literatures',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advanced-search': typeof AdvancedSearchRoute
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/review-generate': typeof ReviewGenerateRoute
  '/review-history': typeof ReviewHistoryRoute
  '/search': typeof SearchRoute
  '/search-history': typeof SearchHistoryRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/literatures': typeof AdminLiteraturesRoute
  '/admin/llm-configs': typeof AdminLlmConfigsRoute
  '/admin/statistics': typeof AdminStatisticsRoute
  '/admin/users': typeof AdminUsersRoute
  '/literature/$id': typeof LiteratureIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advanced-search': typeof AdvancedSearchRoute
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/review-generate': typeof ReviewGenerateRoute
  '/review-history': typeof ReviewHistoryRoute
  '/search': typeof SearchRoute
  '/search-history': typeof SearchHistoryRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/literatures': typeof AdminLiteraturesRoute
  '/admin/llm-configs': typeof AdminLlmConfigsRoute
  '/admin/statistics': typeof AdminStatisticsRoute
  '/admin/users': typeof AdminUsersRoute
  '/literature/$id': typeof LiteratureIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advanced-search': typeof AdvancedSearchRoute
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/review-generate': typeof ReviewGenerateRoute
  '/review-history': typeof ReviewHistoryRoute
  '/search': typeof SearchRoute
  '/search-history': typeof SearchHistoryRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/literatures': typeof AdminLiteraturesRoute
  '/admin/llm-configs': typeof AdminLlmConfigsRoute
  '/admin/statistics': typeof AdminStatisticsRoute
  '/admin/users': typeof AdminUsersRoute
  '/literature/$id': typeof LiteratureIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advanced-search'
    | '/favorites'
    | '/home'
    | '/login'
    | '/profile'
    | '/register'
    | '/review-generate'
    | '/review-history'
    | '/search'
    | '/search-history'
    | '/admin/categories'
    | '/admin/literatures'
    | '/admin/llm-configs'
    | '/admin/statistics'
    | '/admin/users'
    | '/literature/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advanced-search'
    | '/favorites'
    | '/home'
    | '/login'
    | '/profile'
    | '/register'
    | '/review-generate'
    | '/review-history'
    | '/search'
    | '/search-history'
    | '/admin/categories'
    | '/admin/literatures'
    | '/admin/llm-configs'
    | '/admin/statistics'
    | '/admin/users'
    | '/literature/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/advanced-search'
    | '/favorites'
    | '/home'
    | '/login'
    | '/profile'
    | '/register'
    | '/review-generate'
    | '/review-history'
    | '/search'
    | '/search-history'
    | '/admin/categories'
    | '/admin/literatures'
    | '/admin/llm-configs'
    | '/admin/statistics'
    | '/admin/users'
    | '/literature/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvancedSearchRoute: typeof AdvancedSearchRoute
  FavoritesRoute: typeof FavoritesRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ReviewGenerateRoute: typeof ReviewGenerateRoute
  ReviewHistoryRoute: typeof ReviewHistoryRoute
  SearchRoute: typeof SearchRoute
  SearchHistoryRoute: typeof SearchHistoryRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminLiteraturesRoute: typeof AdminLiteraturesRoute
  AdminLlmConfigsRoute: typeof AdminLlmConfigsRoute
  AdminStatisticsRoute: typeof AdminStatisticsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  LiteratureIdRoute: typeof LiteratureIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search-history': {
      id: '/search-history'
      path: '/search-history'
      fullPath: '/search-history'
      preLoaderRoute: typeof SearchHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review-history': {
      id: '/review-history'
      path: '/review-history'
      fullPath: '/review-history'
      preLoaderRoute: typeof ReviewHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review-generate': {
      id: '/review-generate'
      path: '/review-generate'
      fullPath: '/review-generate'
      preLoaderRoute: typeof ReviewGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advanced-search': {
      id: '/advanced-search'
      path: '/advanced-search'
      fullPath: '/advanced-search'
      preLoaderRoute: typeof AdvancedSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/literature/$id': {
      id: '/literature/$id'
      path: '/literature/$id'
      fullPath: '/literature/$id'
      preLoaderRoute: typeof LiteratureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/statistics': {
      id: '/admin/statistics'
      path: '/admin/statistics'
      fullPath: '/admin/statistics'
      preLoaderRoute: typeof AdminStatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/llm-configs': {
      id: '/admin/llm-configs'
      path: '/admin/llm-configs'
      fullPath: '/admin/llm-configs'
      preLoaderRoute: typeof AdminLlmConfigsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/literatures': {
      id: '/admin/literatures'
      path: '/admin/literatures'
      fullPath: '/admin/literatures'
      preLoaderRoute: typeof AdminLiteraturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvancedSearchRoute: AdvancedSearchRoute,
  FavoritesRoute: FavoritesRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ReviewGenerateRoute: ReviewGenerateRoute,
  ReviewHistoryRoute: ReviewHistoryRoute,
  SearchRoute: SearchRoute,
  SearchHistoryRoute: SearchHistoryRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminLiteraturesRoute: AdminLiteraturesRoute,
  AdminLlmConfigsRoute: AdminLlmConfigsRoute,
  AdminStatisticsRoute: AdminStatisticsRoute,
  AdminUsersRoute: AdminUsersRoute,
  LiteratureIdRoute: LiteratureIdRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
